return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "biome",
        "codelldb",
        "gofumpt",
        "goimports",
        "gopls",
        "json-lsp",
        "lua-language-server",
        "luau-lsp",
        "prettier",
        -- "rust-analyzer",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "taplo",
        "typescript-language-server",
        "vue-language-server",
        "zls",
        "detekt",
        "kotlin-lsp",
        "ktlint",
        "gradle-language-server",
        "mdx-analyzer",
      },
      ui = {
        border = "rounded",
      },
    },
  },
  { "mason-org/mason-lspconfig.nvim", opts = {} },
}
